// <auto-generated />
using System;
using CourierMax.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourierMax.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CourierMaxDbContext))]
    partial class CourierMaxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourierMax.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bogotá"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medellín"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cali"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Barranquilla"
                        });
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Distance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tariff")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Distances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationCityId = 2,
                            DistanceKm = 480m,
                            OriginCityId = 1,
                            Tariff = 12000m
                        },
                        new
                        {
                            Id = 2,
                            DestinationCityId = 1,
                            DistanceKm = 480m,
                            OriginCityId = 2,
                            Tariff = 12000m
                        },
                        new
                        {
                            Id = 3,
                            DestinationCityId = 3,
                            DistanceKm = 360m,
                            OriginCityId = 1,
                            Tariff = 9000m
                        },
                        new
                        {
                            Id = 4,
                            DestinationCityId = 1,
                            DistanceKm = 360m,
                            OriginCityId = 3,
                            Tariff = 9000m
                        },
                        new
                        {
                            Id = 5,
                            DestinationCityId = 4,
                            DistanceKm = 950m,
                            OriginCityId = 1,
                            Tariff = 20000m
                        },
                        new
                        {
                            Id = 6,
                            DestinationCityId = 1,
                            DistanceKm = 950m,
                            OriginCityId = 4,
                            Tariff = 20000m
                        },
                        new
                        {
                            Id = 7,
                            DestinationCityId = 3,
                            DistanceKm = 310m,
                            OriginCityId = 2,
                            Tariff = 8000m
                        },
                        new
                        {
                            Id = 8,
                            DestinationCityId = 2,
                            DistanceKm = 310m,
                            OriginCityId = 3,
                            Tariff = 8000m
                        },
                        new
                        {
                            Id = 9,
                            DestinationCityId = 4,
                            DistanceKm = 650m,
                            OriginCityId = 2,
                            Tariff = 15000m
                        },
                        new
                        {
                            Id = 10,
                            DestinationCityId = 2,
                            DistanceKm = 650m,
                            OriginCityId = 4,
                            Tariff = 15000m
                        },
                        new
                        {
                            Id = 11,
                            DestinationCityId = 4,
                            DistanceKm = 900m,
                            OriginCityId = 3,
                            Tariff = 18000m
                        },
                        new
                        {
                            Id = 12,
                            DestinationCityId = 3,
                            DistanceKm = 900m,
                            OriginCityId = 4,
                            Tariff = 18000m
                        });
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.Property<string>("PackageDimensions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PackageVolumeM3")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PackageWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.ShipmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentHistories", (string)null);
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityVolume")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CapacityWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasFilter("[DriverId] IS NOT NULL");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Distance", b =>
                {
                    b.HasOne("CourierMax.Domain.Entities.City", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Domain.Entities.City", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("CourierMax.Domain.Entities.City", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Domain.Entities.City", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("_shipments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.ShipmentHistory", b =>
                {
                    b.HasOne("CourierMax.Domain.Entities.Shipment", "Shipment")
                        .WithMany("History")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("CourierMax.Domain.Entities.Driver", "Driver")
                        .WithOne("Vehicle")
                        .HasForeignKey("CourierMax.Domain.Entities.Vehicle", "DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("_shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
